### PR TITLE
Fix unregistration of event listeners. Fixes #30

### LINKED ISSUE #30: Nucleus causes errors on some of its event listener registration
I am not sure where this problem sprouts from or if it is even problematic, but it does spit out quite a few errors to the console. I couldn't really follow the stacktrace well into what is occurring in Nucleus.

https://gist.github.com/Meronat/10afccb29517684afcdc8ed38f7b2ae5

### PR DESCRIPTION
**Pull request by Meronat**
Fixes #30

### CODE REVIEW

File: src/main/java/org/lanternpowered/server/event/LanternEventManager.java [hunk 1]
```diff
@@ -274,11 +274,9 @@ private void unregister(Predicate<RegisteredListener<?>> unregister) {
             while (it.hasNext()) {
                 final RegisteredListener<?> listener = it.next();
                 if (unregister.test(listener)) {
-                    if (listener.getHandle() instanceof AnnotatedEventListener) {
                         synchronized (this.registeredListeners) {
-                            this.registeredListeners.remove(((AnnotatedEventListener) listener.getHandle()).getHandle());
+                            this.registeredListeners.remove(listener.getHandle());
                         }
```
Comment (Cybermaxke) [inline src/main/java/org/lanternpowered/server/event/LanternEventManager.java]: Can you fix the formatting of the synchronized block, it's 4 spaces to much to the right. After that, I can merge.

Comment (Meronat) [inline src/main/java/org/lanternpowered/server/event/LanternEventManager.java]: Ah yeah I forgot to fix that :P
